apiVersion: v1
kind: Secret
metadata:
    name: testing
    namespace: testing
data:
    secret: ENC[AES256_GCM,data:qP099n8DEUY=,iv:URS3nRqT25T+GbuNo2lLJccVtFnwINhqniKFWmbeXgU=,tag:iVk0aghJtj3CKD7eB38NTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-10T12:41:56Z'
    mac: ENC[AES256_GCM,data:QYkfBHE9HSfyrdyrFGaCRDqKv7RxhfCMpWcPELkcJwMuUpJ/SbQFp6iwrqbo5dEJBszCCkTtHwtOicQ11hJGBxTP+mXRvb4sUyieFQbQx3Z2ZQo2q+WzIrpAwCPMNgso/I+F4AoQV+T2mteuwJWjUR3LzCfv4w8aMCb9rOdQDao=,iv:A4C6mD3nGrxAG4ga8ruKYFcFopXlZ0qXS9et4158oWg=,tag:OcFrk3XH6K2+AiduvYGzQA==,type:str]
    pgp:
    -   created_at: '2020-07-10T12:41:56Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA+9xEWfK9nVoARAARCcZwtXVqXjvt5BvxxEEQCJFKLJjLRIfcQ8dacV/Fhj0
            35hLRxa0NGmgzPFjYwlX+jiIQINN4Lx9MrnUrKjYllftniJ435iS9C7xqhVigrb1
            4dZuKXoD1wmdJi92SpFLv9dZKhi03DTtALl5sCXIaTmzkQ6cwUUrvm1c63i7l3Y9
            wqueFyOs/AuRiuyX5sRfWR7fDnWdzfHErIX2ZrcFo8m/K+W4Aj65L9hrqF0X4BIa
            F7KSM7HPlAvB+g65ISaamx/lard2SMq6wbHn1q0E/nEsOfOCHu2Q+L2/L+nhSMxB
            K81UUY3xFUO6NJUzc9xr5bKTJ9uBeaa9upL1cAPu3XHYjrvZ4dMWDs9vkgu7wnSY
            KHxeiiXEAtUOJ1zYqRCwY/sohd8pACYUjbxND+kyvSwsUSFvpjPugRHbv2+4rO9n
            N+jYvKo7lp1JZ1kDqUmV/5H0T5SOiX000T23U/IOOOone9tXofvJOxX/97rXsl3g
            HauHLoWHdWrHOF5//uobDeRLRZYXWqodeZljS48pg3+4d0BxjOxHt42ddloQhLtJ
            tgGlllI8R3m9HQaTzTuzbGBoFOkM4JoKo09thHfsR1ibfnBCZpDVnBzTDiHewU+W
            J3oHiVidb7kXpevsyiynwzasKJozkKXEtpQsxAISYFvlTeDPak/zL6ZY1PCgNMbS
            4AHklHVAXK0t2VBALSOYWRTfWeGmH+BL4EzhiJHgPOL/KG+i4AXlsPBz4TBcQTIa
            yC5UeAAoCJ9WFJyyJmZ9ax+iEJzV6jngg+QWCC54HvmjVu0dpK3Uy5MW4oPLmDXh
            Rr4A
            =V8Kx
            -----END PGP MESSAGE-----
        fp: ED522181BCEBE66611CD23839581647E383EA6E4
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
